name: Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # reads history for commit changelog

      - uses: BigWigsMods/packager@v2
          
